### ISSUE TITLE
議題

### ISSUE THREAD

**Issue by sakakendo0321** [teamET/2018.perform#108]

**Comment by sakakendo0321** [comment]
fqdnを決める

**Comment by sakakendo0321** [comment]
タスクを分けなおす

**Comment by sakakendo0321** [comment]
仕様書の洗い直し

**Comment by sakakendo0321** [comment]
> fqdnを決める
`kunugida2018` ?

**Comment by sktrombone** [comment]
進捗状況の確認

**Comment by sinbata** [comment]
模擬店mapの詳細決め

**Comment by sinbata** [comment]
現状の確認、これからの方向など全員の意思統一

**Comment by sho0126hiro** [comment]
#113 の確認

**Comment by yosatak** [comment]
fqdnはkfes.jpを持ってるので使いたければ使ってください。結構短くて良い
月末までにお金払わないと失効予定なので使うことわかったら速攻竹内まで教えてください

**Comment by sakakendo0321** [comment]
> fqdnはkfes.jpを持ってるので使いたければ使ってください。結構短くて良い
> 月末までにお金払わないと失効予定なので使うことわかったら速攻竹内まで教えてください

大人の事情で学校のサーバーを使ってくれという話になったので、
ドメインも学校で割り当ててもらいました。
