### ISSUE TITLE
マップページに必要な画像の作成

### ISSUE THREAD

**Issue by sho0126hiro** [teamET/2018.perform#113]
#48 の子供

**Comment by sho0126hiro** [comment]
メモ:
スマホ操作とかで小エリアでも見にくくなったら、map.pngの縦横比をスクエアに近づければ全てのオブジェクトがそれと連動して対応する
（ただし、スクエアに近づけ過ぎるとpcで見にくくなる）

**Comment by sho0126hiro** [comment]
マップ画像作成者の人員増やさないと現状の進捗的にだいぶまずいので明日声かけます。

**Comment by sun-yryr** [comment]
# 画像一覧
---
## 中
- [x] 中 2棟2階
- [x] 中 2棟3階
- [x] 中 2棟4階
- [ ] 中 3棟1階
- [ ] 中 3棟2階
- [ ] 中 3棟3階
- [ ] 中 3棟4階
- [ ] 中 5棟1階
- [ ] 中 5棟2階
- [ ] 中 8棟1階
- [ ] 中 8棟3階
---
## ツール
- [ ] 構内へ  
- [ ] 外 外全体マップへ戻る
- [ ] 中 構内全体マップへ戻る
- [ ] 中 上の階へ
- [ ] 中 下の階へ

**Comment by sho0126hiro** [comment]
山川君が当初必要だと言っていたボタンツール画像を作ってくれました。ありがとう

**Comment by Yamakawa0000** [comment]
廣瀬くん、生きていてくれてありがとう

**Comment by sun-yryr** [comment]
- 構内2棟・3棟の画像作成終了
- 画像サイズを40kb程度に落とした
---
やること
- 上下に余白を作る
  - だいたいどれくらいか欲しい

**Comment by sho0126hiro** [comment]
画像作成終了。後は座標を打つのみ
