### ISSUE TITLE
userの所属を受け取れるようにする

### ISSUE THREAD

**Issue by sakakendo0321** [teamET/2018.perform#130]
slack のmenuを使用する
https://qiita.com/hypermkt/items/b2ffaf610ac92235c4d6#%E3%82%B7%E3%83%B3%E3%83%97%E3%83%AB%E3%81%AA%E3%83%A1%E3%83%8B%E3%83%A5%E3%83%BC%E3%81%AE%E4%BD%9C%E6%88%90
https://api.slack.com/docs/message-menus

**Comment by sktrombone** [comment]
クラスを受け取れるようにした
