### ISSUE TITLE
MAPに使われる画像サイズを落とす

### ISSUE THREAD

**Issue by sho0126hiro** [teamET/2018.perform#166]
#113 の子供
画像サイズが大きいためにWebページがだいぶ重くなってきたので早急に直したい
（解像度・dpi等を落とす）
***画像を作っている人には具体的な連絡を後で入れます***

**Comment by sakakendo0321** [comment]
配信が重いのか、処理が重いのかどっちやろう

**Comment by sho0126hiro** [comment]
プログラムの簡単な流れとしてはこんな感じです。
1．PreloadjsでJSONを全て読み込む
2．canvasのサイズ調整
3．canvasに乗せる全てのオブジェクトをいろんなコンテナ等にセット
（ここで画像データがプログラムに読み込まれる）
（また、ここで画像の縮尺をいじる）
4．ここに来た時点ですべてのオブジェクトがいろんな要素ごとに分かれるコンテナにセットされている
5．クリックイベントを検知
6．今のcanvas要素に対する処理をする（canvas上の全コンテナをcanvasから外す、等）
起きたイベントごとにcanvasに指定するコンテナを格納
7．コンテナに格納したら表示される

１～7の手順は全て同期的に行ってて、画像の読み込みとかに問題が起きている感じじゃなさそう。
1から6までの処理は凄く早いから、7に問題があると思ってる。
7は表示するだけだから単純に表示するのに時間がかかってる。
画像のサイズがかなり重いからじゃないかなぁ（外マップ画像は４Kとか、実際やばい）

**Comment by sho0126hiro** [comment]
その変更はさすがにプログラム書き換えるのほぼ振り出しに戻るので厳しいです。。。

**Comment by sakakendo0321** [comment]
なるほどたしかにそれはあるな、了解

**Comment by sho0126hiro** [comment]
とりあえず画像サイズ落として検証してみる

**Comment by sho0126hiro** [comment]
Active resource loading counts reached to a per-frame limit while the tab is in background. Network requests will be delayed until a previous loading finishes, or the tab is foregrounded. See <URL> for more details
Chromeのコンソールに
こういう表示がでたんだけど、調べてもあんまりよくわからない、大丈夫なのかな…

**Comment by sho0126hiro** [comment]
構外はサクサクなのに構内めちゃ重なんだけど、確実に構内MAPの画像サイズが大きすぎるから一回適当に画像サイズを小さくしてアップロードして下さい

**Comment by sho0126hiro** [comment]
970KBの中TOP画像を51KBまで落としたら死ぬほどサクサクになった。
PCで大画面で開いても問題ない画質にしつつ、ある程度速度の速いものにするために、
後で画像作製組からもう一回出力してもらう

**Comment by sho0126hiro** [comment]
画像めちゃ重問題の修正が入ってかなりサクサクになりました。
有難うMAP画像勢　閉じます。
