### ISSUE TITLE
canvasのRetina対応

### ISSUE THREAD

**Issue by sho0126hiro** [teamET/2018.perform#198]
#48 の子供。
iPhoneなどで見た時にデジタルピクセル比の問題で画質が極端に悪くなる問題があります。

**Comment by Akari000** [comment]
![map](https://user-images.githubusercontent.com/38575274/46392238-a3be4400-c71b-11e8-8fb3-b6f466f17ba4.png)

**Comment by sho0126hiro** [comment]
スマホ・タブレット端末を判定し、LINE＠招待ページに飛ばすようにして、解決しました。
