### ISSUE TITLE
画像保存時に圧縮する

### ISSUE THREAD

**Issue by sakakendo0321** [teamET/2018.perform#290]
アプロードされた画像が大きいときがあるので保存時に圧縮する

**Comment by sakakendo0321** [comment]
imagemagic convertのnode wrapperを使うとよさそう
https://github.com/rsms/node-imagemagick#convertargs-callbackerr-stdout-stderr

**Comment by sktrombone** [comment]
公開の認可をしたときに圧縮する．width=256.
