### ISSUE TITLE
mapで表示されるinformationから「マップを表示」を消す

### ISSUE THREAD

**Issue by sho0126hiro** [teamET/2018.perform#424]

**Comment by sho0126hiro** [comment]
booth.jsonを編集する感じ

**Comment by sakakendo0321** [comment]
booth.jsonってラインのほうから呼び出してるように見えるけど大丈夫か

**Comment by sakakendo0321** [comment]
あー、ここ見る限り別のものになってるし大丈夫か
https://github.com/teamET/2018.perform/blob/65fc37da01d6e2766d898b29d841bfb4f95af1d9/api-server/routes/linebot.js#L47
