### ISSUE TITLE
MAPページ作成

### ISSUE THREAD

**Issue by Akari000** [teamET/2018.perform#48]
#42 のこども
必要な要素を書き出す．
`static/themes/landscape/layout/map.ejs`  を編集．

**Comment by Akari000** [comment]
三段階に分ける

1. 学校全体のマップ
2. 小範囲のマップ
3. 店の詳細

1は `static/themes/landscape/layout/map.ejs` を編集する
2,3 は　`static/themes/landscape/layout/_partial の下にejsファイルを作る．

**Comment by sho0126hiro** [comment]
小マップと全体マップでの行き来は自在にできるようになった。
少し重いので、エリアごとのMAPの画質を少し落としても良いかも。(#113 )

**Comment by sho0126hiro** [comment]
フロア格納用コンテナ：BuildingFloorContainer[][]に正しく格納されず判定が甘くなるバグを修正しました。

**Comment by sho0126hiro** [comment]
構内MAPピンを立てて表示、クリックした構内ピンの判定まで終了しました。
基本的な機能がそろいました。
後は上の階へ行く処理、下の階へ行く処理、その他余裕があれば実装できる箇所を書いていきます。

**Comment by sho0126hiro** [comment]
構内マップ内での上の階へ、下の階へのボタンクリック時に上下の階にジャンプできるようにした。
まだボタンができていないので、後は画像待ち。

**Comment by sho0126hiro** [comment]
PC版として公開します。スマホ版[linebot]と並行開発します。

**Comment by sho0126hiro** [comment]
マップページ完了
