### ISSUE TITLE
模擬店詳細ページ

### ISSUE THREAD

**Issue by Akari000** [teamET/2018.perform#64]
#48  の子ども

**Comment by Akari000** [comment]
- これは変数で呼ぶようにする
  - 商品名
  - 画像のURL
  - 出店者
  - 金額
  - コメント
　
- 周囲の地図へのリンクをはる

**Comment by sakakendo0321** [comment]
https://github.com/teamET/2018.perform/issues/105
これが使えるかもしれない

**Comment by Akari000** [comment]
#113 でやる
