### ISSUE TITLE
タイムテーブルの形式を決める

### ISSUE THREAD

**Issue by Akari000** [teamET/2018.perform#65]
#47 の子ども

とりあえず画像を貼るだけとかでも．．

**Comment by Yamakawa0000** [comment]
[表示形式] 開始時刻ー終了時刻　　　名前　　　所属
[例]　　　17:30 - 18:00     　　JSONBAND    軽音部
[json形式]
        "start-time": "17:30",
        "end-time":  "18:30",
        "name":"JSONBAND",
        "from":"軽音部"

**Comment by Yamakawa0000** [comment]
１つ追加。
土曜日→日曜日のときにファイルの入れ替え面をするのは現実的ではないため、１つのjsonファイルに両日のタイムテーブルを記載する。
そのため、上記の[jsonファイル]の欄に、日付を追加。

**Comment by Akari000** [comment]
@Yamakawa0000  更新日時(update-at)と場所(place)も必要そう
