### ISSUE TITLE
各模擬店にラベルをつけられるようにする

### ISSUE THREAD

**Issue by Akari000** [teamET/2018.perform#70]
#64 の子ども

**Comment by Akari000** [comment]
食べ物
飲み物
アトラクション
あったかいもの
冷たいもの
甘い系
しょっぱい系
などのタグをつける

ラベルは一つの配列にする
模擬店登録の時に複数選択してもらう

**Comment by sktrombone** [comment]
各模擬店の登録時にlabelの登録を行わせるようにした。
