### ISSUE TITLE
模擬店のデータの形式を決める

### ISSUE THREAD

**Issue by Akari000** [teamET/2018.perform#71]

**Comment by Akari000** [comment]
必要なカラムを書き出す
データの形式が決まったらマイグレーションを書く

**Comment by Akari000** [comment]
jsonで保存する

**Comment by sakakendo0321** [comment]
https://github.com/teamET/2018.perform/issues/85#issuecomment-418279146

**Comment by sktrombone** [comment]
//account.json
account = {
	user :{ShopName:"shopname"}
};
//shop.json
shop = {
	shopname : {
		goods: {
			name:"name",
			price:"price"},
		image:"image",
		text:"text"
	}
};
