### ISSUE TITLE
使う写真を入手する（模擬店以外）

### ISSUE THREAD

**Issue by Akari000** [teamET/2018.perform#78]
#77 が終わったらこれをやる

**Comment by Akari000** [comment]
去年の写真を使う

- [ ] スライドショーに使う画像

  　(イベント，MAP，模擬店関連のもの)
- [ ] トップページの一番下のリンクに使う画像
（イベント，模擬店，リンク，アクセス，マップ，椚田祭について）

**Comment by Spacekoki** [comment]
秋の画像
https://drive.google.com/drive/u/1/folders/1PFp4kPmAUYbHSfRDnIJpTxZMrpj0vtDg

**Comment by sakakendo0321** [comment]
挿入した
