### ISSUE TITLE
店舗のデータをjsonで保存する

### ISSUE THREAD

**Issue by sktrombone** [teamET/2018.perform#85]
#83 の子供

**Comment by sakakendo0321** [comment]
jsonで保存した後markdownもしくはhtmlに保存するとejs側での扱いが楽になりそう

**Comment by sktrombone** [comment]
jsonで保存することはできるようになった
各店舗で登録を行えばおっけい

**Comment by sakakendo0321** [comment]
画像,jsonの生成をした後、nginxで扱うために `/root/public/img` とかにコピーして、フロントから受け付けれるようにする必要がありそう
