### ISSUE TITLE
プッシュしたらcircleciを通してデプロイできるようにする。

### ISSUE THREAD

**Issue by sktrombone** [teamET/2018.perform#86]
#83 の子供

**Comment by sakakendo0321** [comment]
circleciでrsync等を利用してサーバーにデプロイできるようにする

雑なメモを
![image](https://user-images.githubusercontent.com/23027593/45585668-232dd400-b923-11e8-95b6-4207651db7e1.png)

**Comment by sakakendo0321** [comment]
#120 に移動
