### ISSUE TITLE
data fileの形式について

### ISSUE THREAD

**Issue by sakakendo0321** [teamET/2018.perform#90]
event,模擬店のincludeされるjson,およびhtmlファイルの仕様について
` 2018.perform/static/data `

**Comment by sakakendo0321** [comment]
```
2018.perform/static/data/event.ejs
```

booth.ejs
https://github.com/teamET/2018.perform/issues/71#issuecomment-418370849

**Comment by sakakendo0321** [comment]
従来の
`{"4J":{"goods":{"banana":"100"},"image":["image"],"text":"text"}};↲`

class名を `name` 受け取れるようにする
`{"name":"4J","goods":{"banana":"100"},"image":["image"],"text":"text"};`

**Comment by sktrombone** [comment]
account = {
		user :{ShopName:"shopname",Class:"class"}
	};
	shop = {
		shopname : {
			goods: {
				name:"price"},
			image:["image"],
			text:"text"
		}
	};

**Comment by sho0126hiro** [comment]
```
{
	"account": {
		"user": {
			"ShopName": "shopname",
			"Class": "class"
		}
	},
	"shop": {
		"shopname": {
			"goods": {
				"name": "price"
			},
			"image": [
				"image"
			],
			"text": "text"
		}
	}
}
```
こうしないと読み込めないよ

**Comment by sktrombone** [comment]
ファイルが存在しなかったときの処理だから本質的な問題にはならないと思うけど、指摘通りには変えておいた。
		account = {
			"user" :{"ShopName":"shopname","Class":"class"}
		};
		shop = {
			"shopname" : {
				"goods": {
					"name":"price"},
				"image":["image"],
				"text":"text"
			}
		};

**Comment by sktrombone** [comment]
eventのほうもslackで対応できるようにするから、event.jsonも作る予定
それについての仕様は近日上げる

**Comment by sho0126hiro** [comment]
account = , shop = は
"account" :  , "shop" : にしないと動作しないので注意
あと、セミコロン消してaccountの閉じかっこの次にカンマを押さないとダメ
Bot周りで読み取れるか分からないけど、MAP側でそれだと読み取れないから
修正しておいてほしいです。。。
JSON整形サイト
https://tools.m-bsys.com/development_tooles/json-beautifier.php
これにぶち込めばJSONの形式間違ってないか判別できるよ

**Comment by sktrombone** [comment]
そこのaccount=とかのあたりはオブジェクトの配列として格納されたjsonデータだから書き方は間違ってないと思うけど。

**Comment by sktrombone** [comment]
account.jsonの中身見てもらえればわかると思うけど、構造は以下の通り。
```
{
	"user": {
		"ShopName": "shopname",
		"Class": "class"
	},
	"UCTP97L87": {
		"ShopName": "test1",
		"Class": "test1"
	},
	"UCSMFLWN6": {
		"ShopName": "entry",
		"Class": "entry"
	}
}
```
