### ISSUE TITLE
bot.jsがきちんと動作しない

### ISSUE THREAD

**Issue by sktrombone** [teamET/2018.perform#97]
startは表示されるが、その後のプログラムが動いていない

**Comment by sktrombone** [comment]
動くようにはなったが、画像ファイルを返すことができてない

**Comment by sakakendo0321** [comment]
👀 みる
引数が間違えてるような気がする、、、このへんの引数名めっちゃ難しいな
https://github.com/teamET/2018.perform/blob/8d4a0416fb9f5ce375fc59d8722439e2eb9ebf4b/bot/bot.js#L148
https://github.com/teamET/2018.perform/blob/8d4a0416fb9f5ce375fc59d8722439e2eb9ebf4b/bot/bot.js#L57

**Comment by sakakendo0321** [comment]
`screen` が受け取った引数をそのまま表示するようにしてみた
```
##### screen file ./files/4x/4x shop_name 4x
screenshot was
ok
(node:3811) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/mnt/c/Users/sakak/workspace/2018.perform/bot/node_modules/puppeteer/.local-chromium/linux-588429/chrome-linux/chrome: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory
```


https://github.com/teamET/2018.perform/blob/8d4a0416fb9f5ce375fc59d8722439e2eb9ebf4b/bot/bot.js#L65-L69
この `Data` を第一引数の `data` にすると動くかな
